### ISSUE TITLE
The plugin doesn't work with proxy server

### ISSUE THREAD

**Issue by BoswachterMarc** [lutraconsulting/qgis-mergin-plugin#123]
I have been reading through the problems (#48 and #57) with the login but I spend a lot of time trying to login and it doesn't work (anymore).

Yesterday I had trouble also but after a reset of the QGIS master password for mergin, I succeeded (by going to Settings > Options. In the new window, I clicked in Authentication tab, and removed the row for mergin).

But now QGIS crashes each times. With a NEW QGIS profile, QGIS doesn't crash anymore but after entering my credentials for Mergin, I got the message 1/ Connection failed, incorrect URL an 2/ 'plugin not configured or QGIS master password not set up'.

I tried with and without saving my credentials. With saving my credentials the QGIS authentification manager said that the master password was read succesfully...

I am working with QGIS 3.4.9 Madeira en Mergin plugin 2020.3.1

![Knipsel4](https://user-images.githubusercontent.com/57868975/77260491-a5b9f100-6c88-11ea-8064-8dbf76823571.PNG)
![Knipsel2](https://user-images.githubusercontent.com/57868975/77260493-a6eb1e00-6c88-11ea-95a3-8389e7d7d15c.PNG)
![Knipsel](https://user-images.githubusercontent.com/57868975/77260494-a783b480-6c88-11ea-8344-66d0887f7b85.PNG)

**Comment by saberraz** [comment]
@BoswachterMarc could you update to version 2020.4.0 and see if the issue still persists?

**Comment by BoswachterMarc** [comment]
> @BoswachterMarc could you update to version 2020.4.0 and see if the issue still persists?

Hi, It's been some time, sorry for that. I updated QGIS to 30.10.8 A Coruna and Mergin plugin to 2020.5.0.
The problem still persists. 
![Knipsel](https://user-images.githubusercontent.com/57868975/91636618-4f549980-ea02-11ea-96b9-377bdd334949.PNG)

**Comment by BoswachterMarc** [comment]
The URL of the server seems to be ok.
![Knipsel](https://user-images.githubusercontent.com/57868975/91636679-cf7aff00-ea02-11ea-9100-0307a00c5a87.PNG)

**Comment by PeterPetrik** [comment]
Hi @BoswachterMarc , 

can you please let me know this information for debugging purposes?

1. You OS version (Windows?)
2. Have you ever managed to login to Mergin through the plugin? If yes, was the bug introduced via some system update. or QGIS update or plugin update?
3. Can you open "Log Messages" Panel (QGIS Menu -> View -> Panels -> Log Messages), and try to test Mergin connection while the panel is opened? It should display the detailed info of the error in one of the tabs of the panel. Please post it here.
4. Open Python Console and type 
```
import json
import urlib
r = urllib.request.Request('https://public.cloudmergin.com/ping')
a = urllib.request.build_opener().open(r)
json.load(a)
```
and please copy the output to this dialog

**Comment by BoswachterMarc** [comment]
Sorry for the delay in reply... The problem persists

1/ OS version windows 10 Enterprise (enterprise pc). I had the same problem before with a Windows 7 enterprise pc.
2/ I think I could login once or twice but not more. Perhaps it is a safety issue because of enterprise pc (although our IT service did install QGis). I can login from another personal computer.
3/ Regular log message 

2020-11-06T11:33:27     INFO    Status toepassing:
             QGIS_PREFIX_PATH omg var: C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr
             Voorvoegsel: C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr
             Pad plug-in: C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/plugins
             Pad gegevenspakket: C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/.
             Naam actieve thema: default
             Pad actieve thema: C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./resources/themes\default\icons/
             Standaard pad thema: :/images/themes/default/
             Paden SVG zoeken: C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./svg/
              C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/svg/
             Gebruiker pad DB: C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./resources/qgis.db
             Auth pad DB: C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/qgis-auth.db
             
2020-11-06T11:35:22     WARNING    Mergin plugin: 
2020-11-06T11:36:15     WARNING    Mergin plugin: 

4/ Python log message

2020-11-06T11:33:17     WARNING    warning:C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\objcreator.py:152: DeprecationWarning: 'U' mode is deprecated
              plugin = open(filename, 'rU')
             
             traceback: File "", line 1, in 
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 354, in startPlugin
              if not _startPlugin(packageName):
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\coordinator\__init__.py", line 35, in classFactory
              from .coordinator import Coordinator
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\coordinator\coordinator.py", line 38, in 
              from .coordinator_dockwidget import CoordinatorDockWidget
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\coordinator\coordinator_dockwidget.py", line 43, in 
              os.path.dirname(__file__), 'coordinator_dockwidget_base.ui'))
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\__init__.py", line 198, in loadUiType
              winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix, import_from)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\Compiler\compiler.py", line 53, in __init__
              qtproxies.QtWidgets, CompilerCreatorPolicy())
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\uiparser.py", line 177, in __init__
              self.factory = QObjectCreator(creatorPolicy)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\objcreator.py", line 85, in __init__
              if self.load_plugin(filename, plugin_globals, plugin_locals):
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\objcreator.py", line 152, in load_plugin
              plugin = open(filename, 'rU')
             
2020-11-06T11:34:18     WARNING    warning:C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\objcreator.py:152: DeprecationWarning: 'U' mode is deprecated
              plugin = open(filename, 'rU')
             
             traceback: File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 489, in configure
              dlg = ConfigurationDialog()
              File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\configuration_dialog.py", line 25, in __init__
              self.ui = uic.loadUi(ui_file, self)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\__init__.py", line 226, in loadUi
              return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\Loader\loader.py", line 51, in __init__
              UIParser.__init__(self, QtCore, QtGui, QtWidgets, LoaderCreatorPolicy(package))
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\uiparser.py", line 177, in __init__
              self.factory = QObjectCreator(creatorPolicy)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\objcreator.py", line 85, in __init__
              if self.load_plugin(filename, plugin_globals, plugin_locals):
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\objcreator.py", line 152, in load_plugin
              plugin = open(filename, 'rU')
             
5/ Python console

import json
import urlib
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'urlib'
r = urllib.request.Request('https://public.cloudmergin.com/ping')
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
NameError: name 'urllib' is not defined
a = urllib.request.build_opener().open(r)
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
NameError: name 'urllib' is not defined

6/ I can login to the Mergin and Input app with my credentials

Regards,
Marc

**Comment by BoswachterMarc** [comment]
See also https://github.com/lutraconsulting/qgis-mergin-plugin/issues/143 and printscreen

![image](https://user-images.githubusercontent.com/57868975/98361795-7b0c8500-202c-11eb-878b-8cd145638172.png)

**Comment by manad93** [comment]
Yes, I have similar or same problem with login - see #143 . 
I have no Amazon certificates in QGIS (see https://github.com/lutraconsulting/qgis-mergin-plugin/issues/143#issuecomment-660904212). I tried to import them manualy from files at https://www.amazontrust.com/repository/, but I can have got only one certificate from file in QGIS at one moment. I have tried them import one by one and for ever of them tride login, but no succes.
But when I trying login nowadays, it raises exception error with "urllib.error.URLError: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required>"
When I tried proposed testing in python console (I repaire a typo mistake in "import urlib" - It have to be "import urllib", I got same exception:
----------------------------------------------------------------------------------------------------------------------------
import json
import urllib
r = urllib.request.Request('https://public.cloudmergin.com/ping')
a = urllib.request.build_opener().open(r)
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 1384, in connect
    super().connect()
  File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 932, in connect
    self._tunnel()
  File "C:\OSGEO4~1\apps\Python37\lib\http\client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 407 Proxy Authentication Required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required>
import json
--------------------------------------------------------------------------------------------------------
I have got right proxy settings in QGIS and I can do requests through a network from QGIS (like fetching a WMS layer).

**Comment by BoswachterMarc** [comment]
Update, two weeks ago a colleague with more experience in enterprise pc and proxy's came up with the simple solution: when making contact with the Mergin server, it is necessary to disable the VPN connection of the enterprise (in my case the GlobalProtect of the corporate network). While doing so, the connection was made flawless :-)

**Comment by manad93** [comment]
> 
> 
> Update, two weeks ago a colleague with more experience in enterprise pc and proxy's came up with the simple solution: when making contact with the Mergin server, it is necessary to disable the VPN connection of the enterprise (in my case the GlobalProtect of the corporate network). While doing so, the connection was made flawless :-)

This workaround it is not possible for me and IMHO for other users.
