### ISSUE TITLE
Error when closing QGIS

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#126]
Error while unloading plugin Mergin 

KeyError: 'Mergin.mergin' 
Traceback (most recent call last):
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 437, in unloadPlugin
    _unloadPluginModules(packageName)
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1115, in __iter__
  File "", line 1103, in _recalculate
  File "", line 1099, in _get_parent_path
KeyError: 'Mergin.mergin'

Python version: 3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008] 
QGIS version: 3.13.0-Master Master, 53075848ce

**Comment by saberraz** [comment]
This is related to the master version of the plugin (with async download).

**Comment by saberraz** [comment]
```
Error while unloading plugin Mergin 

KeyError: 'Mergin.mergin' 
Traceback (most recent call last):
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 437, in unloadPlugin
    _unloadPluginModules(packageName)
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1115, in __iter__
  File "", line 1103, in _recalculate
  File "", line 1099, in _get_parent_path
KeyError: 'Mergin.mergin'

```
