### ISSUE TITLE
Megin plugin installation

### ISSUE THREAD

**Issue by elanioazul** [lutraconsulting/qgis-mergin-plugin#133]
Hi, 
I am having same problem in both qgis 3.10.5-A Coruña and qgis 3.12.2:

Failed to load plugin 'Mergin' due to error calling its classFactory () method
 
ModuleNotFoundError: No module named 'mergin' 
Traceback (most recent call last):
  File "C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\configuration_dialog.py", line 9, in 
    from .mergin.client import MerginClient, ClientError, LoginError
  File "C:/OSGEO4~2/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\__init__.py", line 3, in 
    from .client import MerginClient
  File "C:/OSGEO4~2/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 13, in 
    from pip._vendor import distro
  File "C:/OSGEO4~2/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/OSGEO4~2/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\__init__.py", line 6, in classFactory
    from .plugin import MerginPlugin
  File "C:/OSGEO4~2/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 24, in 
    from .configuration_dialog import ConfigurationDialog
  File "C:/OSGEO4~2/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\configuration_dialog.py", line 15, in 
    from mergin.client import MerginClient, ClientError, LoginError
  File "C:/OSGEO4~2/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'mergin'

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.10.5-A Coruña A Coruña, 984615fe1e 

Ruta de Python:
C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/OSGEO4~2/apps/qgis-ltr/./python
C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~2/apps/qgis-ltr/./python/plugins
C:\OSGEO4~2\apps\Python37
C:\OSGEO4~2\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~2\apps\Python37\DLLs
C:\OSGEO4~2\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~2\apps\Python37\lib\site-packages
C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\hugoh\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\hugoh\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlrd-1.2.0-py2.py3-none-any.whl
C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlwt-1.3.0-py2.py3-none-any.whl
C:/Users/hugoh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\hugoh\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
.
C:\Users\hugoh\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Mergin\mergin_client.whl

I know the option to upload to Mergin data through the web exists also, but this is smoother.
What might be happening?
Thx

**Comment by saberraz** [comment]
What version of plugin are you using? Also, are you downloading the plugin from the QGIS plugin repo?

**Comment by elanioazul** [comment]
Im using 2020.4.0 plugin version. Yes, from qgis plugin repo. 
I'm uninstalling and reinstalling plugin and it says: 
2020-05-05T14:54:22     WARNING    Error de Python : No se pudo cargar el complemento 'Mergin' debido a un error al llamar a su método classFactory() Vea el registro de mensajes (Error de Python) para más detalles.
2020-05-05T14:56:05     INFO    Complemento reinstalado correctamente

But I see all files of the plugin in directories correctly. And you can even read plugin installed correctly in the plugin intaller window.
So, asumming it is well intalled, how to make Mergin icon to appear in browser panel?
Thx!

**Comment by saberraz** [comment]
I can confirm the issue also in a fresh Ubuntu installation
![image](https://user-images.githubusercontent.com/2649047/81148072-80045500-8f73-11ea-9ef0-e40af6f451bd.png)
