### ISSUE TITLE
Mergin plugin crash on QGIS 3.12

### ISSUE THREAD

**Issue by dracic** [lutraconsulting/qgis-mergin-plugin#139]
When I try to unload plugin after plugin installation I get an error:

```
Error while unloading plugin Mergin 

KeyError: 'Mergin.mergin' 
Traceback (most recent call last):
  File "C:/tools/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 437, in unloadPlugin
    _unloadPluginModules(packageName)
  File "C:/tools/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1115, in __iter__
  File "", line 1103, in _recalculate
  File "", line 1099, in _get_parent_path
KeyError: 'Mergin.mergin'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.3-București București, 8234261527 

Python Path:
C:/Users/dracic/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\los_tools
C:/tools/OSGEO4~1/apps/qgis/./python
C:/Users/dracic/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/dracic/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/tools/OSGEO4~1/apps/qgis/./python/plugins
C:\tools\OSGEO4~1\apps\Python37
C:\tools\OSGEO4~1\apps\Python37\Scripts
C:\tools\OSGeo4W64\bin\python37.zip
C:\tools\OSGEO4~1\apps\Python37\DLLs
C:\tools\OSGEO4~1\apps\Python37\lib
C:\tools\OSGeo4W64\bin
C:\tools\OSGEO4~1\apps\Python37\lib\site-packages
C:\tools\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\tools\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\tools\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/dracic/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\dracic\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\dracic\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\dracic\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
.
```

At QGIS startup:

```
Crash ID: 4138dbbf7fd2ac49ca87962a941d43dddd3140fd


Stack Trace


QEventTransitionPrivate::unregister :
QAbstractItemModel::persistentIndexList :
QAbstractItemModelPrivate::rowsInserted :
QAbstractItemModel::endInsertRows :
QMetaObject::activate :
QgsDataItem::populate qgsdataitem.cpp:340
QgsDataItem::childrenCreated qgsdataitem.cpp:315
QMetaObject::activate :
QFutureWatcherBase::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QgsAuthManager::passwordHelperRead qgsauthmanager.cpp:3085
QgsAuthManager::masterPasswordInput qgsauthmanager.cpp:3221
QgsAuthManager::loadAuthenticationConfig qgsauthmanager.cpp:1207
meth_QgsAuthManager_loadAuthenticationConfig sip_corepart2.cpp:189254
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyTuple_New :
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__core_198 sip_corepart0.cpp:19375
sipQgsDataItemProvider::createDataItem sip_corepart3.cpp:221433
QgsBrowserModel::addRootItems qgsbrowsermodel.cpp:142
QgsBrowserModel::initialize qgsbrowsermodel.cpp:197
QgsBrowserDockWidget::showEvent qgsbrowserdockwidget.cpp:127
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QgisApp::QgisApp qgisapp.cpp:1444
main main.cpp:1354
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763
```

**Comment by wonder-sk** [comment]
Thanks for the report... it looks like you are having two separate issues:
- #126 - error message when closing QGIS
- #118 - crash on QGIS start when credentials are saved in QGIS auth manager (there's a workaround mentioned in that ticket)

If that's correct, can we close this ticket? We would post updates on those problems in the existing tickets...

**Comment by dracic** [comment]
Now I see that these are the same. Yes we can close this. Sorry for not reading more carefully.
