### ISSUE TITLE
Exception trying to check out my project

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/qgis-mergin-plugin#160]
Failed to download project tim1/MarvaoHikes due to an unhandled exception.

```
Traceback (most recent call last):

  File "/home/timlinux/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Mergin/sync_dialog.py", line 142, in download_timer_tick
    download_project_finalize(self.job)

  File "/home/timlinux/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client_pull.py", line 199, in download_project_finalize
    task.apply(job.directory, job.mp)

  File "/home/timlinux/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client_pull.py", line 242, in apply
    file_to_merge.merge()

  File "/home/timlinux/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client_pull.py", line 466, in merge
    with open(self.dest_file, 'wb') as final:

FileNotFoundError: [Errno 2] No such file or directory: '/home/timlinux/gisdata/MarvaoHikes/photos/foo.txt'


```

**Comment by timlinux** [comment]
Tested with another project, similar issue:

Traceback (most recent call last):

  File "/home/timlinux/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Mergin/sync_dialog.py", line 142, in download_timer_tick
    download_project_finalize(self.job)

  File "/home/timlinux/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client_pull.py", line 199, in download_project_finalize
    task.apply(job.directory, job.mp)
```
  File "/home/timlinux/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client_pull.py", line 242, in apply
    file_to_merge.merge()

  File "/home/timlinux/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client_pull.py", line 466, in merge
    with open(self.dest_file, 'wb') as final:

FileNotFoundError: [Errno 2] No such file or directory: '/home/timlinux/gisdata/MarvaoMap/fences/foo.txt'

```

**Comment by timlinux** [comment]
By the way I am using QGIS 3.14 installed from flatpack on pop=os

**Comment by timlinux** [comment]
So I could fix by removing the folder 'photos' from the hikes project. That folder contained an empty foo.txt file.

**Comment by timlinux** [comment]
So I could fix by removing the folder 'photos' from the hikes project. That folder contained an empty foo.txt file.

**Comment by timlinux** [comment]
also the above two projects, when failing on check out actually show up as checkd out on re-opening QGIS

![Screenshot from 2020-08-10 14-26-38](https://user-images.githubusercontent.com/178003/89787702-d4d8de00-db15-11ea-9602-f67c1f571875.png)

**Comment by wonder-sk** [comment]
This is indeed being caused by having only a single empty file in a sub-directory (which was not getting created by mistake)
