### ISSUE TITLE
Unhandled exception when getting a template project

### ISSUE THREAD

**Issue by erpas** [lutraconsulting/qgis-mergin-plugin#170]
Failed to download project TEMPLATES/Tree survey due to an unhandled exception.

Windows 10
and 
Wersja QGIS | 3.15.0-Master | Rewizja QGIS | 0a5321abf8
-- | -- | -- | --
Skompilowane z Qt | 5.11.2 | Uruchomione z Qt | 5.11.2
Skompilowane z GDAL/OGR | 3.2.0dev | Uruchomione z GDAL/OGR | 3.2.0dev
Skompilowane z GEOS | 3.8.1-CAPI-1.13.3 | Uruchomione z GEOS | 3.8.1-CAPI-1.13.3
Skompilowane z SQLite | 3.29.0 | Uruchomione z SQLite | 3.29.0
Wersja klienta PostgreSQL | 11.5 | Wersja SpatiaLite | 4.3.0
Wersja QWT | 6.1.3 | Wersja QScintilla2 | 2.10.8
Skompilowane z PROJ | 7.2.0 | Uruchomione z PROJ | Rel. 7.2.0, November 1st, 2020
Wersja systemu operacyjnego | Windows 10 (10.0) | Ta wersja QGIS zapisuje wyjście debugowania.
Aktywne wtyczki Pythona | FibreNetworkDesign2; firstaid; Mergin; plugin_reloader; quick_map_services; db_manager; processing

```
Traceback (most recent call last):

  File "C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 126, in download_timer_tick
    is_running = download_project_is_running(self.job)

  File "C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 170, in download_project_is_running
    _cleanup_failed_download(job.directory)

  File "C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 96, in _cleanup_failed_download
    shutil.rmtree(directory)

  File "C:\OSGEO4~1\apps\Python37\lib\shutil.py", line 507, in rmtree
    return _rmtree_unsafe(path, onerror)

  File "C:\OSGEO4~1\apps\Python37\lib\shutil.py", line 386, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)

  File "C:\OSGEO4~1\apps\Python37\lib\shutil.py", line 391, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())

  File "C:\OSGEO4~1\apps\Python37\lib\shutil.py", line 389, in _rmtree_unsafe
    os.unlink(fullname)

PermissionError: [WinError 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: 'C:\\Users\\<user>\\Documents\\wydra\\projs\\mergin\\Nowy folder\\Tree survey\\.mergin\\client-log.txt'

```

**Comment by wonder-sk** [comment]
@erpas are you still able to replicate?

**Comment by erpas** [comment]
Should now be fixed by https://github.com/lutraconsulting/mergin-py-client/pull/91

**Comment by erpas** [comment]
Although, the underlying problem of the project Tree Survey still prevents a proper project download - namely, it is lack of project version (no history for the project). See https://public.cloudmergin.com/projects/TEMPLATES/Tree%20survey/history
