### ISSUE TITLE
Problem with syncing in QGIS 3.10

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#174]
```
2020-10-31T19:46:06     WARNING    Traceback (most recent call last):
              File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
              h.request(req.get_method(), req.selector, req.data, headers,
              File "/usr/lib/python3.8/http/client.py", line 1255, in request
              self._send_request(method, url, body, headers, encode_chunked)
              File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
              self.endheaders(body, encode_chunked=encode_chunked)
              File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
              self._send_output(message_body, encode_chunked=encode_chunked)
              File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
              self.send(msg)
              File "/usr/lib/python3.8/http/client.py", line 950, in send
              self.connect()
              File "/usr/lib/python3.8/http/client.py", line 1417, in connect
              super().connect()
              File "/usr/lib/python3.8/http/client.py", line 921, in connect
              self.sock = self._create_connection(
              File "/usr/lib/python3.8/socket.py", line 787, in create_connection
              for res in getaddrinfo(host, port, 0, SOCK_STREAM):
              File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
              for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
             socket.gaierror: [Errno -2] Naam of dienst is niet bekend
             
```
During handling of the above exception, another exception occurred:
```
             
             Traceback (most recent call last):
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 131, in _do_request
              return self.opener.open(request)
              File "/usr/lib/python3.8/urllib/request.py", line 525, in open
              response = self._open(req, data)
              File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
              result = self._call_chain(self.handle_open, protocol, protocol +
              File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
              result = func(*args)
              File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
              return self.do_open(http.client.HTTPSConnection, req,
              File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
              raise URLError(err)
             urllib.error.URLError: 
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py", line 348, in sync_project
              pull_changes, push_changes, push_changes_summary = self.mc.project_status(self.path)
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 426, in project_status
              server_info = self.project_info(project_path, since=local_version)
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 333, in project_info
              resp = self.get("/v1/project/{}".format(project_path), params)
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 146, in get
              return self._do_request(request)
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 114, in wrapper
              return f(self, *args)
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 139, in _do_request
              raise ClientError("Error requesting " + request.full_url + ": " + str(e))
             Mergin.mergin.common.ClientError: Error requesting https://public.cloudmergin.com/v1/project/Mergin_USER/MERGIN_Project?since=v2: 
```

**Comment by saberraz** [comment]
@BoswachterMarc I trust this can be closed now. Feel free to re-open if you still experience some problems.
