### ISSUE TITLE
QGIS Sync error

### ISSUE THREAD

**Issue by HugoP27** [lutraconsulting/qgis-mergin-plugin#179]
please report the problemTraceback (most recent call last):

  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 416, in apply_pull_changes
    self.geodiff.rebase(basefile, src, dest, rebase_conflicts)

  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 105, in rebase
    return self.clib.rebase(base, modified_their, modified, conflict)

  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 165, in rebase
    _parse_return_code(res, "rebase")

  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: rebase

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 310, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 523, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 431, in apply_pull_changes
    os.remove(f'{dest}-wal')

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\hugop\\Documents\\jobfiles\\09-jobs\\De Rust\\De Rust Grid Setup 10.2020\\input\\DeRustGrid.gpkg-wal'

**Comment by wonder-sk** [comment]
Thanks for the report. Do you have some more details on how did you get this issue? And is there any chance that the mentioned data file (DeRustGrid.gpkg) was opened by some other software at the same time?

**Comment by wonder-sk** [comment]
Also, please could you submit the diagnostic log of the project? You can do that by right-clicking the project in the browser panel in QGIS and clicking "Diagnostic log" in the context menu - that should help us to get to the bottom of the problem.

**Comment by HugoP27** [comment]
Hi, thanks for the response, I closed h

**Comment by HugoP27** [comment]
Hi I deleted and recreated the project but the problem has not happened again. I think it might have been open in a different app..

Thank you
