### ISSUE TITLE
SYNC ERROR

### ISSUE THREAD

**Issue by ARSTTESTPITS** [lutraconsulting/qgis-mergin-plugin#180]
Hi
When I try to sync the project from within QGIS I get this error. It wont download data whcih I can see on my phone...
Any clues on how to sort this?

Many thanks in anticipation
Details below

Failed to sync project AXXXXXPITS/BXXXXXit due to an unhandled exception.
This should not happen, please report the problem.

the extra details are

Traceback (most recent call last):

  File "C:/Users/rxxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 415, in apply_pull_changes
    self.geodiff.create_changeset(basefile, src, server_diff)

  File "C:/Users/rxxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 65, in create_changeset
    return self.clib.create_changeset(base, modified, changeset)

  File "C:/Users/rxxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 125, in create_changeset
    _parse_return_code(res, "createChangeset")

  File "C:/Users/rxxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: createChangeset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:/Users/rxxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 310, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/rxxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 523, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:/Users/rxxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 431, in apply_pull_changes
    os.remove(f'{dest}-wal')

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rxxxxxxx\\Desktop\\Dxxxxxn files\\tpsurvey\\TPbatsurvey.gpkg-wal'

**Comment by saberraz** [comment]
Closed due to lack of feedback.
