### ISSUE TITLE
SSL problem on MacOS 3.16.1 [fixed]

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-mergin-plugin#185]
```
An error has occurred while executing Python code: 

AttributeError: module 'ssl' has no attribute '_create_default_https_context' 
Traceback (most recent call last):
  File "/Users/peter/Library/Application Support/QGIS/QGIS3/profiles/new2/python/plugins/Mergin/configuration_dialog.py", line 48, in accept
    err_msg = validate_mergin_url(self.server_url())
  File "/Users/peter/Library/Application Support/QGIS/QGIS3/profiles/new2/python/plugins/Mergin/utils.py", line 205, in validate_mergin_url
    if not mc.is_server_compatible():
  File "/Users/peter/Library/Application Support/QGIS/QGIS3/profiles/new2/python/plugins/Mergin/mergin/client.py", line 162, in is_server_compatible
    resp = self.get("/ping")
  File "/Users/peter/Library/Application Support/QGIS/QGIS3/profiles/new2/python/plugins/Mergin/mergin/client.py", line 146, in get
    return self._do_request(request)
  File "/Users/peter/Library/Application Support/QGIS/QGIS3/profiles/new2/python/plugins/Mergin/mergin/client.py", line 114, in wrapper
    return f(self, *args)
  File "/Users/peter/Library/Application Support/QGIS/QGIS3/profiles/new2/python/plugins/Mergin/mergin/client.py", line 131, in _do_request
    return self.opener.open(request)
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/urllib/request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/urllib/request.py", line 1287, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/http/client.py", line 1391, in __init__
    context = ssl._create_default_https_context()
AttributeError: module 'ssl' has no attribute '_create_default_https_context'


Python version: 3.7.7 (default, Sep 22 2020, 10:25:18) [Clang 12.0.0 (clang-1200.0.32.2)] 
QGIS version: 3.16.0-Hannover Hannover, 33475aa559 

Python Path:
/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python
/Users/peter/Library/Application Support/QGIS/QGIS3/profiles/new2/python
/Users/peter/Library/Application Support/QGIS/QGIS3/profiles/new2/python/plugins
/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/cftime-1.2.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/pyproj-2.6.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/click_plugins-1.1.1-py3.7.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/snuggs-1.4.7-py3.7.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/affine-2.3.0-py3.7.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/rasterio-1.1.5-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/geopandas-0.8.1-py3.7.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/opencv_contrib_python-4.3.0.36-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/Fiona-1.8.13.post1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/statsmodels-0.11.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/Pillow-7.2.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/pandas-1.1.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/numpy-1.19.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/netCDF4-1.5.3-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/lib-dynload
/Applications/QGIS3.16.app/Contents/MacOS/lib/python37.zip
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/scipy-1.5.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages
/Users/peter/.local/lib/python3.7/site-packages
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/patsy-0.5.1-py3.7.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/numba-0.50.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/Rtree-0.9.4-py3.7.egg
/Applications/QGIS3.16.app/Contents/MacOS/lib/python3.7/site-packages/matplotlib-3.3.0-py3.7-macosx-10.13.0-x86_64.egg
/Users/peter/Library/Application Support/QGIS/QGIS3/profiles/new2/python
.
```

**Comment by PeterPetrik** [comment]
workaround

1. open `/Applications/QGIS3.16.app/Contents/Resources/python/ssl.py` in the text editor 
2. add `from _ssl2 import _create_default_https_context` at the end of file
3. save
4. restart QGIS

will be fixed in QGIS 3.16.2 and tomorrow's nightly
