### ISSUE TITLE
No se pudo sincronizar el usuario / proyecto del proyecto debido a una excepción no controlada.

### ISSUE THREAD

**Issue by mascarcelen** [lutraconsulting/qgis-mergin-plugin#198]
Desde España, al sincronizar con el PC indica: 

Traceback (most recent call last):

  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 294, in pull_timer_tick
    is_running = pull_project_is_running(self.job)

  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 440, in pull_project_is_running
    raise future.exception()

  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 86, in _do_download
    item.download_blocking(mc, mp, project_path)

  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 281, in download_blocking
    save_to_file(resp, self.download_file_path)

  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\utils.py", line 36, in save_to_file
    with open(path, 'wb') as output:

PermissionError: [Errno 13] Permission denied: 'X:\\Input\\tdagtes\\.mergin\\fetch_v21-v26\\DCIM\\tdagtes_2021-02-19T19:54:04.725.jpg.0'

**Comment by mascarcelen** [comment]
Este mismo error me lo indica desde otro PC: 
Traceback (most recent call last):

  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 126, in download_timer_tick
    is_running = download_project_is_running(self.job)

  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 170, in download_project_is_running
    _cleanup_failed_download(job.directory)

  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 96, in _cleanup_failed_download
    shutil.rmtree(directory)

  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 507, in rmtree
    return _rmtree_unsafe(path, onerror)

  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 386, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)

  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 391, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())

  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 389, in _rmtree_unsafe
    os.unlink(fullname)

PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\Input\\tdagtes\\tdagtes\\.mergin\\client-log.txt'

**Comment by mascarcelen** [comment]
Si realizo cualquier actualización de cambios con input desde una tablet o móvil no da problemas

**Comment by mascarcelen** [comment]
No he podido descargar el proyecto de Mergin, me indica esto: 
Traceback (most recent call last):

  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 126, in download_timer_tick
    is_running = download_project_is_running(self.job)

  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 170, in download_project_is_running
    _cleanup_failed_download(job.directory)

  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 96, in _cleanup_failed_download
    shutil.rmtree(directory)

  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 507, in rmtree
    return _rmtree_unsafe(path, onerror)

  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 386, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)

  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 391, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())

  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 389, in _rmtree_unsafe
    os.unlink(fullname)

PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\Input\\tdagtes\\.mergin\\client-log.txt'

**Comment by saberraz** [comment]
This indicates that you do not have permission to write to that specific path. Could you make sure you have write access to the folder AND it is not a network drive?

**Comment by wonder-sk** [comment]
Related error reported in #170 - also with permission error to client-log.txt
