### ISSUE TITLE
Enable to re-install plugin

### ISSUE THREAD

**Issue by katagen** [lutraconsulting/qgis-mergin-plugin#215]
I have a problem when I want to re-install the plugin. Here is the python error code:
Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'NoneType' object has no attribute 'mc' 
Traceback (most recent call last):
  File "C:/Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 236, in on_qgis_project_changed
    self.enable_toolbar_actions(enable=False)
  File "C:/Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 195, in enable_toolbar_actions
    if self.data_item_provider.root_item.mc is None:
AttributeError: 'NoneType' object has no attribute 'mc'

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.16.5-Hannover Hannover, 58ba7c1ed6 

Chemin Python :
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\stoant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\stoant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:/Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\stoant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
.
C:/Users/stoant/AppData/Roaming/QGIS/QGIS3/profiles/default

**Comment by katagen** [comment]
I realize it’s the same bug as ticket #214
