### ISSUE TITLE
Better error message reporting

### ISSUE THREAD

**Issue by AesculusK** [lutraconsulting/qgis-mergin-plugin#216]
https://www.loom.com/share/f0a50b05855d4b38b3e2f47ccea21e44

**Comment by AesculusK** [comment]
Traceback (most recent call last):

  File "C:/Users/kathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 226, in push_timer_tick
    push_project_finalize(self.job)

  File "C:/Users/kathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_push.py", line 238, in push_project_finalize
    job.mp.apply_push_changes(job.changes)

  File "C:/Users/kathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 496, in apply_push_changes
    shutil.copy(self.fpath(path), basefile)

  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))

shutil.SameFileError: 'G:\\My Drive\\Clients\\Studio3\\0 Tourney Loop\\0 Tourney Loop GIS\\0 Tourney\\Survey_points.gpkg' and 'G:\\My Drive\\Clients\\Studio3\\0 Tourney Loop\\0 Tourney Loop GIS\\0 Tourney\\.mergin\\Survey_points.gpkg' are the same file

**Comment by AesculusK** [comment]
This error was resolved by recreating my Mergin project. Apparently if I georeference my own maps, they need to be packaged to work in Mergin - which is totally fine, but a more specific error message would be useful. Thanks!

**Comment by AesculusK** [comment]
Oops, didn't mean to close this...I still want a more specific error message! GitHub rookie :)

**Comment by wonder-sk** [comment]
This error has been fixed (https://github.com/lutraconsulting/mergin-py-client/commit/f8cb0ab1e47cc39decb51c6fb54eb541c709dea7) and starting from the next release of the Mergin plugin, it should not happen anymore...
