### ISSUE TITLE
Crash syncing on QGIS Master

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/qgis-mergin-plugin#220]
Hi Guys

I am getting a crash trying to sync on QGIS master. I can share a stack trace, don't know how useful it will be:

```
Error while reading shared library symbols for /lib64/libpthread.so.0:
Cannot find user-level thread for LWP 33949: generic error
0x00007f227e299e1f in wait4 () from /lib64/libc.so.6
[Current thread is 1 (LWP 33892)]
#0  0x00007f227e299e1f in wait4 () at /lib64/libc.so.6
#1  0x000000000040d23e in qgisCrash(int) (signal=11) at /home/timlinux/dev/cpp/QGIS/src/app/main.cpp:350
        status = 32545
        pidstr = "--pid=33892\000\001", '\000' <repeats 18 times>
        gdbpid = 33976
        exename = "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/bin/qgis\000\"\177\000\000\030\342-\000\000\000\000\000\000\000\000\000\001\000\000\000\020\000\000\000\377\177\000\000\200\342)\035\377\177\000\000@\342)\035\377\177\000\000\000\326ň5\004\244}\030\342-\000\000\000\000\000\000\000\000\000\001\000\000\000\240\342)\035\377\177", '\000' <repeats 18 times>, "\070\a\030\006\065\223\333\t(\026*\002\000\000\000\000\255\252\202\177\"\177", '\000' <repeats 11 times>, "\326ň5\004\244}\001\000\000\000\006\000\000\000X\354"...
        len = 59
#2  0x00007f227e20a310 in <signal handler called> () at /lib64/libc.so.6
#3  0x0000000000000000 in  ()
#4  0x00007f21e48d4eb0 in sqlite3Malloc.part.5 () at /home/timlinux/.local/share/QGIS/QGIS3/profiles/Smallholding/python/plugins/Mergin/mergin/deps/pygeodiff/libpygeodiff-0.8.6-python.so
#5  0x00007f21e4927b5f in sessionReadRecord () at /home/timlinux/.local/share/QGIS/QGIS3/profiles/Smallholding/python/plugins/Mergin/mergin/deps/pygeodiff/libpygeodiff-0.8.6-python.so
#6  0x00007f21e492948e in sessionChangesetNext.part.608 () at /home/timlinux/.local/share/QGIS/QGIS3/profiles/Smallholding/python/plugins/Mergin/mergin/deps/pygeodiff/libpygeodiff-0.8.6-python.so
#7  0x00007f21e49cd86b in GEODIFF_hasChanges () at /home/timlinux/.local/share/QGIS/QGIS3/profiles/Smallholding/python/plugins/Mergin/mergin/deps/pygeodiff/libpygeodiff-0.8.6-python.so
#8  0x00007f2278fd3c04 in ffi_call_unix64 () at /lib64/libffi.so.6
#9  0x00007f2278fd3107 in ffi_call () at /lib64/libffi.so.6
#10 0x00007f2111ba8f0c in _ctypes_callproc.cold () at /usr/lib64/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so
#11 0x00007f2111bb2163 in PyCFuncPtr_call () at /usr/lib64/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so
#12 0x00007f227eb8ecd7 in _PyObject_MakeTpCall () at /lib64/libpython3.9.so.1.0
#13 0x00007f227eb8b78e in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#14 0x00007f227eb93653 in function_code_fastcall () at /lib64/libpython3.9.so.1.0
#15 0x00007f227eb86c20 in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#16 0x00007f227eb93653 in function_code_fastcall () at /lib64/libpython3.9.so.1.0
#17 0x00007f227eb86c20 in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#18 0x00007f227eb8564d in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#19 0x00007f227eb9333e in _PyFunction_Vectorcall () at /lib64/libpython3.9.so.1.0
#20 0x00007f227eb86c20 in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#21 0x00007f227eb93653 in function_code_fastcall () at /lib64/libpython3.9.so.1.0
#22 0x00007f227eb86c20 in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#23 0x00007f227eb8564d in _PyEval_EvalCode () at /lib64/libpython3.9.so.1.0
#24 0x00007f227eb9333e in _PyFunction_Vectorcall () at /lib64/libpython3.9.so.1.0
#25 0x00007f227eb86c20 in _PyEval_EvalFrameDefault () at /lib64/libpython3.9.so.1.0
#26 0x00007f227eb93653 in function_code_fastcall () at /lib64/libpython3.9.so.1.0
#27 0x00007f227eb9b9c2 in method_vectorcall () at /lib64/libpython3.9.so.1.0
#28 0x00007f2110f0bd28 in PyQtSlot::invoke(void**, _object*, void*, bool) const () at /usr/lib64/python3.9/site-packages/PyQt5/QtCore.so
#29 0x00007f2110f0fe2e in PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) () at /usr/lib64/python3.9/site-packages/PyQt5/QtCore.so
#30 0x00007f2288658282 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt5Core.so.5
#31 0x00007f22890af686 in QAction::triggered(bool) () at /lib64/libQt5Widgets.so.5
#32 0x00007f22890b1f70 in QAction::activate(QAction::ActionEvent) () at /lib64/libQt5Widgets.so.5
#33 0x00007f228922ffea in QMenuPrivate::activateCausedStack(QVector<QPointer<QWidget> > const&, QAction*, QAction::ActionEvent, bool) () at /lib64/libQt5Widgets.so.5
#34 0x00007f2289237612 in QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) () at /lib64/libQt5Widgets.so.5
#35 0x00007f22890f685e in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#36 0x00007f22890b5e73 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#37 0x00007f22890bd5ad in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#38 0x00007f228544036b in QgsApplication::notify(QObject*, QEvent*) (this=0x7fff1d2a1320, receiver=0x6e383f0, event=0x7fff1d2a02f0) at /home/timlinux/dev/cpp/QGIS/src/core/qgsapplication.cpp:479
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#39 0x00007f2288627f48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#40 0x00007f22890bbe6a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib64/libQt5Widgets.so.5
#41 0x00007f228910f3a0 in QWidgetWindow::handleMouseEvent(QMouseEvent*) () at /lib64/libQt5Widgets.so.5
#42 0x00007f22891121fe in QWidgetWindow::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#43 0x00007f22890b5e73 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#44 0x00007f228544036b in QgsApplication::notify(QObject*, QEvent*) (this=0x7fff1d2a1320, receiver=0x226b3e0, event=0x7fff1d2a06d0) at /home/timlinux/dev/cpp/QGIS/src/core/qgsapplication.cpp:479
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#45 0x00007f2288627f48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#46 0x00007f2288a62a08 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib64/libQt5Gui.so.5
#47 0x00007f2288a444fc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Gui.so.5
#48 0x00007f21e7492124 in userEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5WaylandClient.so.5
#49 0x00007f227d8e24cf in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#50 0x00007f227d9364e8 in g_main_context_iterate.constprop () at /lib64/libglib-2.0.so.0
#51 0x00007f227d8dfc03 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#52 0x00007f22886746f8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#53 0x00007f22886269b2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#54 0x00007f228862e544 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#55 0x0000000000414c7f in main(int, char**) (argc=1, argv=0x7fff1d2a26a8) at /home/timlinux/dev/cpp/QGIS/src/app/main.cpp:1646
        preApplicationLogMessages = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x2026ae0}, d = 0x2026ae0}}, <No data fields>}
        __FUNCTION__ = "main"
        mySnapshotFileName = {d = 0x7f22886ea260 <QArrayData::shared_null>}
        configLocalStorageLocation = {d = 0x202dc70}
        profileName = {d = 0x202c450}
        mySnapshotWidth = 800
        mySnapshotHeight = 600
        myHideSplash = false
        settingsMigrationForce = false
        mySkipVersionCheck = false
        hideBrowser = false
        myRestoreDefaultWindowState = false
        myRestorePlugins = true
        myCustomization = true
        dxfOutputFile = {d = 0x7f22886ea260 <QArrayData::shared_null>}
        dxfSymbologyMode = QgsDxfExport::SymbolLayerSymbology
        dxfScale = 50000
        dxfEncoding = {d = 0x420a60 <main::{lambda()#2}::operator()() const::qstring_literal>}
        dxfMapTheme = {d = 0x7f22886ea260 <QArrayData::shared_null>}
        dxfExtent = {mXmin = 0, mYmin = 0, mXmax = 0, mYmax = 0}
        takeScreenShots = false
        screenShotsPath = {d = 0x7f22886ea260 <QArrayData::shared_null>}
        screenShotsCategories = 0
        myInitialExtent = {d = 0x420aa0 <main::{lambda()#3}::operator()() const::qstring_literal>}
        translationCode = {d = 0x205d770}
        authdbdirectory = {d = 0x7f22886ea260 <QArrayData::shared_null>}
        pythonfile = {d = 0x7f22886ea260 <QArrayData::shared_null>}
        customizationfile = {d = 0x2a4e1d0}
        globalsettingsfile = {d = 0x2026400}
        args = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x2026d00}, d = 0x2026d00}}, <No data fields>}
        myUseGuiFlag = true
        rootProfileFolder = {d = 0x202db90}
        manager = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7f22888e43e0 <QObject::staticMetaObject>}, stringdata = 0x7f2285ec5d20 <qt_meta_stringdata_QgsUserProfileManager>, data = 0x7f2285ec5da0 <qt_meta_data_QgsUserProfileManager>, static_metacall = 0x7f2284e0f58e <QgsUserProfileManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mWatchProfiles = false, mWatcher = std::unique_ptr<QFileSystemWatcher> = {get() = 0x0}, mRootProfilePath = {d = 0x202db90}, mUserProfile = std::unique_ptr<QgsUserProfile> = {get() = 0x0}, mSettings = std::unique_ptr<QSettings> = {get() = 0x2026c90}}
        profile = 0x202dd70
        profileFolder = {d = 0x2030160}
        myApp = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7f22895ba4c0 <QApplication::staticMetaObject>}, stringdata = 0x7f2285eb5660 <qt_meta_stringdata_QgsApplication>, data = 0x7f2285eb5860 <qt_meta_data_QgsApplication>, static_metacall = 0x7f2284dfa02a <QgsApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mIconCache = {d = 0x2193060}, mCursorCache = {d = 0x34d3d10}, mQgisTranslator = 0x21c3350, mQtTranslator = 0x220cde0, mDataItemProviderRegistry = 0x2cf3f10, mAuthManager = 0x2fae1e0, mApplicationMembers = 0x21a5c00}
        settings = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7f22888e43e0 <QObject::staticMetaObject>}, stringdata = 0x7f2285ec12e0 <qt_meta_stringdata_QgsSettings>, data = 0x7f2285ec1320 <qt_meta_data_QgsSettings>, static_metacall = 0x7f2284e0a87a <QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x21c39e0, mGlobalSettings = 0x20a8f50, mUsingGlobalArray = false}
        libPaths = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x298df20}, d = 0x298df20}}, <No data fields>}
        relLibPath = {d = 0x2a360d0}
        customizationsettings = 0x2991990
        systemEnvVars = {d = 0x23e27f0}
        useCustomVars = false
        desiredStyle = {d = 0x421880 <main::{lambda()#42}::operator()() const::qstring_literal>}
        theme = {d = 0x28573f0}
        activeStyleName = {d = 0x324fa40}
        mySplashPath = {d = 0x7f228601bea0 <QgsApplication::splashPath()::{lambda()#1}::operator()() const::qstring_literal>}
        myPixmap = <incomplete type>
        w = 600
        h = 300
        mypSplash = 0x20b7ae0
        qgis = 0x334f4a0
        sigwatch = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7f22888e43e0 <QObject::staticMetaObject>}, stringdata = 0x462380 <qt_meta_stringdata_UnixSignalWatcher>, data = 0x462440 <qt_meta_data_UnixSignalWatcher>, static_metacall = 0x41c2ba <UnixSignalWatcher::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = 0x3d82650}
        retval = -2007399373
[Inferior 1 (process 33892) detached]
gdb returned 0
Aborted (core dumped)



```

Basically as soon as I press sync in the project context menu, QGIS becomes unresponsive, then a little while later, crashes out. Here is my QGIS version details:

QGIS version | 3.19.0-Master | QGIS code revision | c8b891b8a1
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.34.1
PostgreSQL Client Version | 13.2 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Fedora 34 (Workstation Edition) | This copy of QGIS writes debugging output.
Active python plugins | geetimeseriesexplorer; Mergin; ee_plugin; quick_map_services; MetaSearch; processing; db_manager

**Comment by wonder-sk** [comment]
@timlinux is that happening reproducibly? With only one project or with multiple projects?

A crash somewhere inside sqlite3 means there is something going wrong really horribly... I guess this is your self-compiled QGIS. Could you please try with a released version, e.g. QGIS 3.16 or 3.18 ?

**Comment by wonder-sk** [comment]
Please try again with the new plugin version 2021.4 - this part has been reworked, so it should not crash there anymore...
