### ISSUE TITLE
When changing the mergin server, synchronization of projects fails

### ISSUE THREAD

**Issue by jozefbudac** [lutraconsulting/qgis-mergin-plugin#221]
Steps tu reproduce:

1) connect mergin plugin to public server and download a project. 
2) try to synchronize changes with the server. It shoud be ok
3) configure mergin plugin to use different server
4) download the projects. it should be ok
5) try to add some changes to project and synchronize it with the server. 
6) now error appears:

 2021-04-19T09:49:41     WARNING    Traceback (most recent call last):
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 131, in _do_request
              return self.opener.open(request)
              File "/usr/lib/python3.8/urllib/request.py", line 531, in open
              response = meth(req, response)
              File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
              response = self.parent.error(
              File "/usr/lib/python3.8/urllib/request.py", line 569, in error
              return self._call_chain(*args)
              File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
              result = func(*args)
              File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
              raise HTTPError(req.full_url, code, msg, hdrs, fp)
             urllib.error.HTTPError: HTTP Error 404: NOT FOUND
             
During handling of the above exception, another exception occurred:
             
     Traceback (most recent call last):
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py", line 439, in sync_project
              self.mpm.sync_project(self.path, self.project_name)
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/projects_manager.py", line 183, in sync_project
              pull_changes, push_changes, push_changes_summary = self.mc.project_status(project_dir)
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 470, in project_status
              server_info = self.project_info(project_path, since=local_version)
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 332, in project_info
              resp = self.get("/v1/project/{}".format(project_path), params)
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 146, in get
              return self._do_request(request)
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 114, in wrapper
              return f(self, *args)
              File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 135, in _do_request
              raise ClientError(info.get("detail"))
             Mergin.mergin.common.ClientError: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by erpas** [comment]
Nice one. Users usually do not change their server while working on a project. 
Nevertheless, it should be handled properly.
