### ISSUE TITLE
Failed to sync project due to an unhandled exception SameFileError

### ISSUE THREAD

**Issue by GGaeke** [lutraconsulting/qgis-mergin-plugin#224]
**ERROR DETAILS**
Traceback (most recent call last):

  File "C:/Users/ggaeke/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 310, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/ggaeke/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 511, in pull_project_finalize
    shutil.copy(basefile, server_file)

  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))

shutil.SameFileError: 'H:\\TRF 3120\\Sample_GC\\.mergin\\Irrigation.gpkg' and 'H:\\TRF 3120\\Sample_GC\\.mergin\\fetch_v1-v2\\Irrigation.gpkg' are the same file

**Comment by wonder-sk** [comment]
This has been likely fixed by the recent release of Mergin plugin (2021.2) - I will close this ticket now, but please feel free to reopen if the problem still exists after upgrade...
