### ISSUE TITLE
Sync error when locally removing a file that was removed on server

### ISSUE THREAD

**Issue by gubuntu** [lutraconsulting/qgis-mergin-plugin#232]
Steps to reproduce:
- create a mergin project with some files
- download the project with mergin plugin
- delete one file in the project directory and delete the same file through the web interface
- try to sync - the sync will fail, trying to remove a file that does not exist anymore:

```
Traceback (most recent call last):

  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/sync_dialog.py", line 310, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client_pull.py", line 541, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/merginproject.py", line 469, in apply_pull_changes
    os.remove(dest)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/Shared/data/GIZ/LandTenureIS_Madagascar/JPEG_20210413_180438_5302820920624137478.jpg'
```

**Comment by wonder-sk** [comment]
A related issue is that this error is not getting recorded to the diagnostic log - that should get also fixed.
