### ISSUE TITLE
Error during creation of new project

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/qgis-mergin-plugin#274]
Version: 2021.4
System: Ubuntu 20.04.2 LTS

Steps to reproduce:
1) create new project with mergin plugin
2) choose 1st option: "New basic QGIS project"
3) set a project name and hit finish

Stack trace:

An error has occurred while executing Python code: 

OSError: libsqlite3.so: cannot open shared object file: No such file or directory 
Traceback (most recent call last):
  File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/8.7./python/plugins/Mergin/create_project_wizard.py", line 486, in accept
    self.project_manager.create_project(
  File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/8.7./python/plugins/Mergin/projects_manager.py", line 95, in create_project
    mp = MerginProject(project_dir)
  File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/8.7./python/plugins/Mergin/mergin/merginproject.py", line 46, in __init__
    self.geodiff = pygeodiff.GeoDiff()
  File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/8.7./python/plugins/Mergin/mergin/deps/pygeodiff/main.py", line 25, in __init__
    self.clib = GeoDiffLib(libname)
  File "/home/shockwave/.local/share/QGIS/QGIS3/profiles/8.7./python/plugins/Mergin/mergin/deps/pygeodiff/geodifflib.py", line 62, in __init__
    self.lib = ctypes.CDLL(self.libname, use_errno=True)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libsqlite3.so: cannot open shared object file: No such file or directory

Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0] 
QGIS version: 3.16.8-Hannover Hannover, 8c50902ea4 

Python Path:
/usr/share/qgis/python
/home/shockwave/.local/share/QGIS/QGIS3/profiles/8.7./python
/home/shockwave/.local/share/QGIS/QGIS3/profiles/8.7./python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/shockwave/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/shockwave/.local/share/QGIS/QGIS3/profiles/8.7./python
.
/home/shockwave/Lutra/projects/mergin_plugin/8.7./plugin_project

**Comment by jozef-budac** [comment]
Fixed in latest version
