### ISSUE TITLE
Failed  to download first project

### ISSUE THREAD

**Issue by lbraun** [lutraconsulting/qgis-mergin-plugin#299]
Hello! I just started using mergin on my android phone and am trying to download my first project onto my MacBook Pro (M1 chip) running MacOS 11.6. I am using QGIS 3.10 and installed the mergin plugin following the instructions [here](https://help.cloudmergin.com/quick-start.html). When I get to the download step and select the download location, I get the following error:

![image](https://user-images.githubusercontent.com/294776/134780905-510bf07e-9820-4de2-8588-d8ddd0b04b2c.png)

Here's the full traceback:

```
Traceback (most recent call last):

  File "/Users/lucas/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/sync_dialog.py", line 99, in download_start_internal
    self.job = download_project_async(self.mergin_client, self.project_name, self.target_dir)

  File "/Users/lucas/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client_pull.py", line 118, in download_project_async
    mp = MerginProject(directory)

  File "/Users/lucas/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/merginproject.py", line 46, in __init__
    self.geodiff = pygeodiff.GeoDiff()

  File "/Users/lucas/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/deps/pygeodiff/main.py", line 25, in __init__
    self.clib = GeoDiffLib(libname)

  File "/Users/lucas/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/deps/pygeodiff/geodifflib.py", line 62, in __init__
    self.lib = ctypes.CDLL(self.libname, use_errno=True)

  File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: dlopen(/Users/lucas/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/deps/pygeodiff/libpygeodiff-1.0.3-python.dylib, 6): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /Users/lucas/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/deps/pygeodiff/libpygeodiff-1.0.3-python.dylib
  Expected in: /usr/lib/libsqlite3.dylib
 in /Users/lucas/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/deps/pygeodiff/libpygeodiff-1.0.3-python.dylib
```

Thanks in advance for your help!

**Comment by saberraz** [comment]
We no longer support QGIS 3.10. Could you please update to QGIS 3.16 please?
