### ISSUE TITLE
Can't sync project

### ISSUE THREAD

**Issue by BoswachterMarc** [lutraconsulting/qgis-mergin-plugin#301]
I am having some sync problems. 
Here are two messages because after the first one, I upgraded the Mergin plug-in but the issue persists.

1/ Issue with Mergin plug-in 2021.4.1 on QGIS 3.16.3 Hannover.

Traceback (most recent call last):

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 415, in apply_pull_changes
    self.geodiff.create_changeset(basefile, src, server_diff)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 65, in create_changeset
    return self.clib.create_changeset(base, modified, changeset)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 125, in create_changeset
    _parse_return_code(res, "createChangeset")

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: createChangeset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 310, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 523, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 431, in apply_pull_changes
    os.remove(f'{dest}-wal')

PermissionError: [WinError 32] Het proces heeft geen toegang tot het bestand omdat het door een ander
proces wordt gebruikt: 'C:\\Users\\Struelma\\Documents\\QGisCloudSurvey\\MiradalCloudSurvey_V2.4\\MiradalCloudSurvey.gpkg-wal'

---

2/ Same issue after upgrading the mergin plug-in to 2021.4.2 on 3.16.3 Hannover.

Traceback (most recent call last):

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 437, in apply_pull_changes
    self.geodiff.create_changeset(basefile, src, server_diff)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 65, in create_changeset
    return self.clib.create_changeset(base, modified, changeset)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 200, in create_changeset
    _parse_return_code(res, "createChangeset")

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: createChangeset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 306, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 555, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 445, in apply_pull_changes
    self.geodiff.make_copy_sqlite(f_conflict_file, dest)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 221, in make_copy_sqlite
    return self.clib.make_copy_sqlite(src, dst)

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 328, in make_copy_sqlite
    _parse_return_code(res, "make_copy_sqlite")

  File "C:/Users/Struelma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite

**Comment by BoswachterMarc** [comment]
I experienced the sync problem on a windows 10 enterprise pc. But this moment I tried with a linux Mint 20 Xfce 64-bit with the same Qgis version 3.16.3 Hannover and the Mergin plug-in 2021.4.2 installed. **Syncing was ok!**

**Comment by wonder-sk** [comment]
Duplicate of #327
