### ISSUE TITLE
Failed to sync project due to unhandled exception.

### ISSUE THREAD

**Issue by djambar** [lutraconsulting/qgis-mergin-plugin#302]
Hi @wonder-sk , @saberraz 

I have this error when synch after modifying a form.

Failed to sync project due to unhandled exception.
This should not happen, please report the problem.

Traceback (most recent call last):

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 438, in apply_pull_changes
    self.geodiff.rebase(basefile, src, dest, rebase_conflicts)

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 105, in rebase
    return self.clib.rebase(base, modified_their, modified, conflict)

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 240, in rebase
    _parse_return_code(res, "rebase")

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: rebase

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 306, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 555, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 445, in apply_pull_changes
    self.geodiff.make_copy_sqlite(f_conflict_file, dest)

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 221, in make_copy_sqlite
    return self.clib.make_copy_sqlite(src, dst)

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 328, in make_copy_sqlite
    _parse_return_code(res, "make_copy_sqlite")

  File "C:\Users/Utilisateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite

**Comment by djambar** [comment]
duplicate issue

**Comment by djambar** [comment]
The solution provided in issue #284 does not work  (delete the project directory and re-download the Mergin project)
