### ISSUE TITLE
Fail to connect

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#309]
`Connection failed, failure reason: Tunnel connection failed: 407 authenticationrequired`
![image](https://user-images.githubusercontent.com/2649047/139930572-d46401ee-349f-488c-b0dc-6dc46ecdbac8.png)

**Comment by PeterPetrik** [comment]
@saberraz is this usability problem (like wrong message) or bug as such?

**Comment by mascarcelen** [comment]
Hola, no se que me pasa en Qgis 16 que al instalar Mergin y querer conectarme me indica este error: 


Ha ocurrido un error mientras se ejecutaba el código de Python: 

AttributeError: 'NoneType' object has no attribute 'split' 
Traceback (most recent call last):
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\configuration_dialog.py", line 48, in accept
    err_msg = validate_mergin_url(self.server_url())
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\utils.py", line 330, in validate_mergin_url
    mc = MerginClient(url, proxy_config=get_qgis_proxy_config(url))
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\utils.py", line 191, in get_qgis_proxy_config
    excluded = [e.rstrip("/") for e in s.value("proxy/proxyExcludedUrls", "").split("|")]
AttributeError: 'NoneType' object has no attribute 'split'


Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.16.8-Hannover Hannover, 8c50902ea4 

Ruta de Python:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins 

Alquien me puede informar qué puede pasar?
Gracias

**Comment by saberraz** [comment]
The plugin appears to use only HTTP and HTTP Caching proxy. We should support the DefaultProxy settings from QGIS too.

**Comment by saberraz** [comment]
@mascarcelen yes, this error happens when you set the HTTP proxy. So that too seems broken.

**Comment by wonder-sk** [comment]
There seem to be two problems:
- if QGIS uses default proxy - this is not supported by plugin currently - but should be easy to do by just using default proxy settings from urllib https://docs.python.org/3.5/howto/urllib2.html#proxies
- parsing of excluded urls may be incorrect (the reported python error)

**Comment by saberraz** [comment]
This appears to be affecting lots of users. There are several reports of failure to download the project.
