### ISSUE TITLE
Geodiff is not installed properly

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#320]
An error has occurred while executing Python code:
```
AttributeError: function 'GEODIFF_init' not found

Traceback (most recent call last):
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\create_project_wizard.py", line 486, in accept
    self.project_manager.create_project(
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\projects_manager.py", line 95, in create_project
    mp = MerginProject(project_dir)
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 46, in __init__
    self.geodiff = pygeodiff.GeoDiff()
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 25, in __init__
    self.clib = GeoDiffLib(libname)
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 63, in __init__
    self.init()
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 161, in init
    func = self.lib.GEODIFF_init
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'GEODIFF_init' not found


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
QGIS version: 3.20.1-Odense Odense, 1c3c5cd6

Python Path:

·                     C:/PROGRA~1/QGIS32~1.1/apps/qgis/./python

·                     C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python

·                     C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins

·                     C:/PROGRA~1/QGIS32~1.1/apps/qgis/./python/plugins

·                     C:\Program Files\QGIS 3.20.1\bin\python39.zip

·                     C:\PROGRA~1\QGIS32~1.1\apps\Python39\DLLs

·                     C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib

·                     C:\Program Files\QGIS 3.20.1\bin

·                     C:\PROGRA~1\QGIS32~1.1\apps\Python39

·                     C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages

·                     C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\win32

·                     C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\win32\lib

·                     C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\Pythonwin

·                     C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by jozef-budac** [comment]
I tried to installed the same version of QGIS (3.20.1) and python (3.9.5) on the Windows 10 and installation and synchronization of the plugin goes well. So probably, the installation of QGIS and python is somehow damage on the user side, so geodiff was not loaded properly. 

Also mergin plugin is supported on LTR (currently 3.16) and LR (currently 3.22), so probably good way to fix this problem would be have new clear installation of QGIS in one of this versions and install mergin plugin there.

**Comment by PeterPetrik** [comment]
3.20 is not longer supported, we support 3.22 LTR now
