### ISSUE TITLE
Sync breaks after database schema change (make_copy_sqlite error)

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-mergin-plugin#327]
Steps to reproduce:
1. user A downloads a project
2. user A adds a new feature to the project (but does not sync yet)
3. user B modifies database schema (e.g. adds a column to a table in geopackage) and syncs
4. user A syncs - this will first fail to rebase (which is fine) but then also fail when creating conflict copy - it will cause an unexpected sync error:

![sync-after-schema-change](https://user-images.githubusercontent.com/193367/150357147-ab46e64a-38b2-4140-bdb0-8bfcbe47dd9c.png)

After that, due to the unexpected sync error, the project directory is left in a broken state and further syncs are not successful.

This only happens on Windows - on this system, files that are currently open can't get deleted (replaced).

The full python error:
```
Traceback (most recent call last):

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 437, in apply_pull_changes
    self.geodiff.create_changeset(basefile, src, server_diff)

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 65, in create_changeset
    return self.clib.create_changeset(base, modified, changeset)

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 200, in create_changeset
    _parse_return_code(res, "createChangeset")

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: createChangeset


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 306, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 555, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 445, in apply_pull_changes
    self.geodiff.make_copy_sqlite(f_conflict_file, dest)

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 221, in make_copy_sqlite
    return self.clib.make_copy_sqlite(src, dst)

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 328, in make_copy_sqlite
    _parse_return_code(res, "make_copy_sqlite")

  File "C:/Users/martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite
```

This bug has been already reported a couple of times, but without steps how to reproduce it: #284 #300 #301 #305 #319 #326

**Comment by wonder-sk** [comment]
To be addressed when https://github.com/lutraconsulting/mergin-py-client/issues/117 is implemented.

The plugin should add some extra handling:
- if pull does not finish completely (because copying fails), try to close project, finish the pull and load the project again
- do not allow going to push if pull does not finish completely
- in status dialog, if there is unfinished pull, show a big warning
- if sync is run and there is unfinished pull, try to finish previous pull
- [optional] show exclamation mark in browser for project with unfinished pull, add an action to popup menu to finish it (?)
- [optional] when project is loaded and has unfinished full, show a message bar about it with a button to finish it (?)
