### ISSUE TITLE
Can't write to shared project with writer rights

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/qgis-mergin-plugin#358]
When user have a shared project with **writer** rights, he is not able to write into it with this error:

```
An error has occurred while executing Python code: 

AttributeError: 'MerginClient' object has no attribute 'has_writing_permissions' 
Traceback (most recent call last):
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/15.3.22/python/plugins/Mergin/plugin.py", line 300, in current_project_sync
    self.manager.sync_project(self.mergin_proj_dir)
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/15.3.22/python/plugins/Mergin/projects_manager.py", line 271, in sync_project
    if any(push_changes.values()) and not self.mc.has_writing_permissions(project_name):
AttributeError: 'MerginClient' object has no attribute 'has_writing_permissions'


Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0] 
QGIS version: 3.22.4-Białowieża Białowieża, ce8e65e95e 

Python Path:
/usr/share/qgis/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/15.3.22/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/15.3.22/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/jozef/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/jozef/.local/share/QGIS/QGIS3/profiles/15.3.22/python
.
/home/jozef/Lutra/projects/21.3.22/share3

**Comment by jozef-budac** [comment]
Builded with wrong py-client
