### ISSUE TITLE
Unable to synchronize 

### ISSUE THREAD

**Issue by qnmai** [lutraconsulting/qgis-mergin-plugin#378]
I am unable to synchronize my project. This may or may not have been after updating the plugin as this is a new project.

QGIS 3.22 on Windows 10 with the last version of mergin updated 14 april, 2022.

This is the error message in the QGIS python console:

```
Une erreur est survenue lors de l'éxécution du code Python: 

json.decoder.JSONDecodeError: Invalid control character at: line 144 column 32 (char 3304) 
Traceback (most recent call last):
  File "C:\Users/internet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 491, in sync_project
    self.project_manager.project_status(self.path)
  File "C:\Users/internet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\projects_manager.py", line 164, in project_status
    validation_results = validator.run_checks()
  File "C:\Users/internet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\validation.py", line 88, in run_checks
    self.check_db_schema()
  File "C:\Users/internet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\validation.py", line 216, in check_db_schema
    has_change, msg = has_schema_change(self.mp, layer)
  File "C:\Users/internet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\utils.py", line 909, in has_schema_change
    base_schema = json.load(f).get('geodiff_schema')
  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 144 column 32 (char 3304)


Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.22.5-Białowieża Białowieża, c2723178 

Chemin Python :
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python
C:/Users/internet/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/internet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.5\bin\python39.zip
C:\PROGRA~1\QGIS32~1.5\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib
C:\PROGRA~1\QGIS32~1.5\bin
C:\PROGRA~1\QGIS32~1.5\apps\Python39
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/internet/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/internet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\internet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
C:\Users\internet\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
E:/INPUT/SIG_SPL_input/SIG_SPL_test
```
.

**Comment by qnmai** [comment]
Same issue with the version updated on 12 april 2022.

**Comment by wonder-sk** [comment]
hi @qnmai thanks for the report! Would it be possible to share your Mergin project with `support` account on Mergin, so that we can investigate the root of the problem?

**Comment by qnmai** [comment]
okay, just did so.

**Comment by wonder-sk** [comment]
Thanks, what is the name of the project?

**Comment by qnmai** [comment]
SIG_SPL_test

**Comment by alexbruy** [comment]
This happens because some field names contain caret return character. When geodiff lib exports schema to JSON such field names lead to broken JSON output.
