### ISSUE TITLE
Error message upon uploading new project

### ISSUE THREAD

**Issue by qnmai** [lutraconsulting/qgis-mergin-plugin#381]
I receive an error message when uploading a project. Issue seems related to the project. I wonder if it is because we are using aggregate formulas.

Using QGIS 3.22 with Mergin Plugin 2022.1.

This is the error in a msg box:
`Client error: Error requesting https://public.cloudmergin.com/v1/project/push/chunk/8a1423d4-b64e-4e28-a798-b2c528518d41/09e2d62c-01d3-4cd7-b049-88f9a1b5e708: <urlopen error [Errno 11001] getaddrinfo failed>`

I believe this error in the console is related, but I'm not totally sure:
```
2022-04-18T10:30:08     WARNING    warning:C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\utils.py:434: DeprecationWarning: QgsVectorFileWriter.writeAsVectorFormatV2() is deprecated
              res, err = QgsVectorFileWriter.writeAsVectorFormatV2(layer, layer_filename, transform_context, writer_opts)
             
             traceback: File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\plugin.py", line 288, in create_new_project
              if not wizard.exec_():
              File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\create_project_wizard.py", line 480, in accept
              package_layer(layer, self.project_dir)
              File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\utils.py", line 613, in package_layer
              fname, err = save_vector_layer_as_gpkg(layer, project_dir, update_datasource=True)
              File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\utils.py", line 434, in save_vector_layer_as_gpkg
              res, err = QgsVectorFileWriter.writeAsVectorFormatV2(layer, layer_filename, transform_context, writer_opts)
             
```

**Comment by qnmai** [comment]
It may be due to a max file size, if there is a limit? I've manually uploaded it to mergin cloud without the big file and shared with support. thank you

**Comment by qnmai** [comment]
Using QGIS 3.22 with Mergin Plugin 2022.1

However, I seem to get the same error using the latest version as well...

**Comment by qnmai** [comment]
I've tested another project as well. I get the same error with the latest version and 2022.1 version, but it seems to take more time before sending the error (task bar advances before showing message box).

Client error: Error requesting https://public.cloudmergin.com/v1/project/push/chunk/52fb3c3c-599c-40aa-bfd5-6cf3b659645d/16e35f5a-ba6b-4958-b663-51f3175609ff: <urlopen error [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant>

I'll try to manually upload the project and share with support.

**Comment by qnmai** [comment]
More tests (going back to a project that works and started making modifications) and the error message has changed a bit:

![image](https://user-images.githubusercontent.com/20867587/166065600-695b033b-b986-4ed4-a200-74dd73d8316f.png)


Traceback (most recent call last):

  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\sync_dialog.py", line 206, in push_timer_tick
    is_running = push_project_is_running(self.job)

  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\mergin\client_push.py", line 229, in push_project_is_running
    raise future.exception()

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\mergin\client_push.py", line 324, in _do_upload
    item.upload_blocking(job.mc, job.mp)

  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\mergin\client_push.py", line 69, in upload_blocking
    resp = mc.post("/v1/project/push/chunk/{}/{}".format(self.transaction_id, self.chunk_id), data, headers)

  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\mergin\client.py", line 210, in post
    return self._do_request(request)

  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\mergin\client.py", line 178, in wrapper
    return f(self, *args)

  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\Mergin\mergin\client.py", line 188, in _do_request
    return self.opener.open(request)

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\urllib\request.py", line 1350, in do_open
    r = h.getresponse()

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)

  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

**Comment by qnmai** [comment]
modifications don't seem to be the problem (ex: adding layers--project with same layer added fails, then succeeds).

**Comment by alexbruy** [comment]
Are you behind proxy? If yes, can you share proxy settings you are using in QGIS?

**Comment by qnmai** [comment]
We are not behind a proxy.
