### ISSUE TITLE
Python error when hitting enter after sync

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/qgis-mergin-plugin#405]
After I hit sync button in plugin and immediately hit Enter after it, I probably hit "Cancel" button in plugin and get this error
I believe, users can get to it more often.
This is not critical thing, as user can sync again without problems

```
An error has occurred while executing Python code: 

AssertionError 
Traceback (most recent call last):
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/scaling/python/plugins/Mergin/sync_dialog.py", line 59, in cancel_operation
    self.pull_cancel()
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/scaling/python/plugins/Mergin/sync_dialog.py", line 314, in pull_cancel
    assert self.job
AssertionError


Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] 
QGIS version: 3.22.6-Białowieża Białowieża, b6f33b1a9f 

Python Path:
/usr/share/qgis/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/scaling/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/scaling/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/jozef/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/jozef/.local/share/QGIS/QGIS3/profiles/scaling/python
/home/jozef/Lutra/projects/a/plugin_local_project
.

**Comment by alexbruy** [comment]
I'm pretty sure this existed in all previous versions too, but was not tested before.

**Comment by jozef-budac** [comment]
Yes, I believe it also :)
