### ISSUE TITLE
Python error when trying to delete a local project

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#63]
`2019-11-06T10:59:23     WARNING    An error has occurred while executing Python code:
             
             
             AttributeError: 'NoneType' object has no attribute 'mc'
             
             
             Traceback (most recent call last):
              File "C:/Users/windows10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 280, in createChildren
              item = MerginProjectItem(self, project)
              File "C:/Users/windows10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 72, in __init__
              self.mc = self.parent().parent().mc
             AttributeError: 'NoneType' object has no attribute 'mc'
             
             
             
             
             Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
             
             
             QGIS version: 3.4.13-Madeira Madeira, 64ad560274
             
             
             Python Path:
             
             C:/OSGEO4~1/apps/qgis-ltr/./pythonC:/Users/windows10/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonC:/Users/windows10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/pluginsC:/OSGEO4~1/apps/qgis-ltr/./python/pluginsC:\OSGeo4W64\bin\python37.zipC:\OSGEO4~1\apps\Python37\DLLsC:\OSGEO4~1\apps\Python37\libC:\OSGeo4W64\binC:\OSGEO4~1\apps\Python37C:\OSGEO4~1\apps\Python37\lib\site-packagesC:\OSGEO4~1\apps\Python37\lib\site-packages\win32C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\libC:\OSGEO4~1\apps\Python37\lib\site-packages\PythonwinC:/Users/windows10/AppData/Roaming/QGIS/QGIS3\profiles\default/python.C:/Users/windows10/Downloads/def3`

**Comment by saberraz** [comment]
Probably the reason for it, is that I had it open. Maybe, before deleting the local project, we need to check if it is open.

**Comment by tastrax** [comment]
Similar issue - windows 10

2019-11-19T09:31:54     WARNING    Traceback (most recent call last):
              File "C:/Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 128, in remove_local_project
              shutil.rmtree(self.path)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 507, in rmtree
              return _rmtree_unsafe(path, onerror)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 386, in _rmtree_unsafe
              _rmtree_unsafe(fullname, onerror)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 391, in _rmtree_unsafe
              onerror(os.unlink, fullname, sys.exc_info())
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\shutil.py", line 389, in _rmtree_unsafe
              os.unlink(fullname)
             PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:\\GIS DataBase\\Projects\\InputProjects\\Farming V3\\Farming V3\\.mergin\\FarmCapture.gpkg-diff-8509fda8-3c88-424d-97df-320ec50ebab7'
