### ISSUE TITLE
Error Loading Plugin

### ISSUE THREAD

**Issue by kevin-garcia** [lutraconsulting/qgis-mergin-plugin#71]
Plugin installs fine, but won't load. I'm running QGIS on LXLE (based on Ubuntu 16.04).

Here's the full extent of the message:

Couldn't load plugin 'Mergin' due to an error when calling its classFactory() method 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/flash/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/__init__.py", line 6, in classFactory
    from .plugin import MerginPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/flash/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py", line 156
    pull_msg += f"added: {pull_added} \n"
                                        ^
SyntaxError: invalid syntax

Python version: 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609] 
QGIS version: 3.5.0-Master Master, ea9d5bb 

Python Path:
/home/flash/.local/share/QGIS/QGIS3/profiles/default/python/plugins/networks
/home/flash/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ClusterPoints
/usr/share/qgis/python
/home/flash/.local/share/QGIS/QGIS3/profiles/default/python
/home/flash/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-i386-linux-gnu
/usr/lib/python3.5/lib-dynload
/home/flash/.local/lib/python3.5/site-packages
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
/home/flash/.local/share/QGIS/QGIS3/profiles/default/python
/home/flash/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms

**Comment by kevin-garcia** [comment]
I decided to upgrade my OS to the newest version of LXLE, based on Ubuntu 18.04, and after installing QGIS 3.10, the plugin loaded fine.
