### ISSUE TITLE
Problem with installing master

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#96]
I am trying to test the master branch and after building the plugin and installing it, I get this error:

```
Traceback (most recent call last):
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: module 'Mergin' has no attribute 'classFactory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/local/src/QGIS_master/build/output/python/pyplugin_installer/installer.py", line 630, in installFromZipFile
    startPlugin(pluginName)
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 354, in startPlugin
    if not _startPlugin(packageName):
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 336, in _startPlugin
    _unloadPluginModules(packageName)
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 448, in _unloadPluginModules
    mods = _plugin_modules[packageName]
KeyError: 'Mergin'


Python version:
3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008]

QGIS version:
3.11.0-Master 'Master', 3f9b53ea73
```

**Comment by saberraz** [comment]
To reproduce that, you will need to delete the old plugin and install the new one as a zip file.

I have restarted QGIS and re-installed the plugin and the bug has disappeared. But nevertheless, it is still an annoying thing.
